### ISSUE TITLE
Log prometheus version

### ISSUE THREAD

**Issue by grobie** [ncabatoff/prombench#1]
The prometheus binary has a `-version` flag to print build and version information. Prombench could parse that and print the version:

```
./prometheus -version
prometheus, version 1.1.2 (branch: master, revision: 03855679a10540da91fe99ec6a1027f064dc67a8)
  build user:       grobie@grobook
  build date:       20160915-02:12:31
  go version:       go1.7.1
```

**Comment by ncabatoff** [comment]
I think it should become a metric, along with config settings (maybe all Prometheus command line args with numeric values?).  It's just easier to have all the data in one place, and Prometheus handles unchanging metrics well.

**Comment by grobie** [comment]
You mean reading these information from metrics? Interesting idea. We do have [prometheus_build_info](http://demo.prometheus.io:9090/graph?g0.range_input=1h&g0.expr=prometheus_build_info&g0.tab=1). Not sure about storing all config options, but you could create an issue for that.

We planned to extend the HTTP Json API to provide all build, config, rules, etc. information.

If the server doesn't even start or at least when the query interface isn't available, it would still be beneficial to log the version. That's why I'd suggest to read the information from the cli.

**Comment by ncabatoff** [comment]
I was actually speaking of prombench exporting metrics for all command-line arguments it was given to override the defaults.  And sure, it can also log the output of prometheus -version.
