### ISSUE TITLE
Allow running mixed load of exporters

### ISSUE THREAD

**Issue by grobie** [ncabatoff/prombench#3]
It's currently only possible to run one kind of exporter at a time. If it were possible to repeat the `-exporter` flag (and/or accept a comma-separated list), we could run different exporter types.

In order to control the number of exporters, we could drop the `-num-exporters` flag and create a new flag value type `{{exporter}}:{{number}}` for example.

```
prombench -exporter inc:4 -exporter randcyclic:1
```

**Comment by ncabatoff** [comment]
Agreed.

**Comment by ncabatoff** [comment]
My latest commit fixes this issue.  And yes, I've just learned after the fact that you can say "Fixes x" in the commit message... still new to Github.
